name: Build

on:
  push:
    branches: [main]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 检出代码
        uses: actions/checkout@v7

      - name: 准备 Typst
        uses: typst-community/setup-typst@v5

      - name: 构建 PDF
        run: make all

      - name: 上传 PDF
        uses: actions/upload-artifact@v7
        with:
          name: Todd-s-Avali-Lore-Guide-V1.7_chinese
          path: ./main.pdf
